name: Release Publish
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - run: npm ci
      - uses: JS-DevTools/npm-publish@0fd2f4369c5d6bcfcde6091a7c527d810b9b5c3f # v4.1.5
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
  build_container:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Docker Meta Data
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: meta
        with:
          tags: |
            type=semver,event=tag,pattern={{version}}
          flavor: |
            latest=true
          images: |
            flowfuse/mqtt-schema-agent
      - name: Setup QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Docker login
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
        with:
          username: flowfuse
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: docker
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          platforms: linux/amd64,linux/arm64
      - name: Publish README.md to Docker Hub
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          repository: flowfuse/mqtt-schema-agent
          username: flowfuse
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          readme-filepath: ./README.md

  notify-slack:
    name: Notify about release failure
    needs: [publish, build_container]
    if: failure()
    runs-on: ubuntu-latest

    steps:
    - name: Notify Slack
      uses: FlowFuse/github-actions-workflows/actions/slack_notification@slack_notification/v1
      with:
        bot-token: ${{ secrets.SLACK_GHBOT_TOKEN }}
        mode: channel
        blocks: |
          [
            { "type": "header", "text": { "type": "plain_text", "text": ":x: ${{ github.workflow }} workflow failed", "emoji": true } },
            { "type": "divider" },
            { "type": "section", "text": { "type": "mrkdwn", "text": "<${{ github.server_url }}/${{ github.repository }}/actions/workflows/release-publish.yml|${{ github.workflow }}> workflow failed to complete successfully." } },
            { "type": "section", "text": { "type": "mrkdwn", "text": "*Workflow run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View>" } }
          ]
